# Generated by Django 6.1 on 2026-08-29 13:17

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('media_type', models.CharField(blank=True, max_length=32)),
                ('alt_text', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('reposts', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('mastodon', 'Mastodon'), ('bluesky', 'Bluesky'), ('rss', 'RSS')], max_length=32)),
                ('external_id', models.CharField(help_text='Account ID on the source platform', max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('access_token', models.CharField(blank=True, max_length=1024)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform', 'handle'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'platform', 'external_id'), name='unique_account_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('mastodon', 'Mastodon'), ('bluesky', 'Bluesky'), ('rss', 'RSS')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_handle', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('posted_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', django_mongodb_backend.fields.EmbeddedModelField(blank=True, embedded_model='feeds.metrics', null=True)),
                ('media', django_mongodb_backend.fields.ArrayField(base_field=django_mongodb_backend.fields.EmbeddedModelField(embedded_model='feeds.mediaitem'), blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Original payload from the source platform')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='feeds.account')),
            ],
            options={
                'ordering': ['-posted_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'platform', 'external_id'), name='unique_post_per_account')],
            },
        ),
    ]
