# Generated by Django 6.1 on 2026-08-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.CharField(choices=[('x', 'X'), ('facebook', 'Facebook'), ('mastodon', 'Mastodon'), ('bluesky', 'Bluesky'), ('rss', 'RSS')], max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('x', 'X'), ('facebook', 'Facebook'), ('mastodon', 'Mastodon'), ('bluesky', 'Bluesky'), ('rss', 'RSS')], max_length=32),
        ),
    ]
