# Generated by Django 6.1 on 2026-08-29 21:42

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_account_platform_alter_post_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonApp',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_domain', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Platform-specific extras, e.g. Mastodon instance domain'),
        ),
    ]
