# Generated by Django 6.1 on 2026-08-29 23:10

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_mastodonapp_account_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=django_mongodb_backend.fields.EmbeddedModelArrayField(blank=True, embedded_model='feeds.mediaitem', null=True),
        ),
    ]
