# Generated by Django 6.1 on 2026-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_alter_mediaitem_url_alter_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_own',
            field=models.BooleanField(default=False, help_text="True if this is a post the account itself made, synced via the 'My posts' feed rather than the friends/home-timeline feed."),
        ),
    ]
